#!/usr/bin/env python3

import os
import sys
import subprocess

init_file = "/usr/bin/_orbicreo/__init__.py"

def main():
    if os.path.isfile(init_file):
        subprocess.call([init_file, os.getcwd()] + sys.argv[1:])
    else:
        print("Executable file '" + init_file + "' not found")

if __name__ == "__main__":
    main()